# Generated by Django 4.0.4 on 2022-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_time_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='second',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
