# Generated by Django 4.0.4 on 2022-05-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_hour_task_minute_task_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
    ]
