# Generated by Django 4.0.4 on 2022-05-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hour',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='minute',
            new_name='minutes',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='second',
            new_name='seconds',
        ),
    ]
