# Generated by Django 4.0.4 on 2022-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_hour_task_hours_rename_minute_task_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.CharField(blank=True, default='⭕️', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
