# Generated by Django 4.0.4 on 2022-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='To Do', max_length=20, null=True),
        ),
    ]
