# Generated by Django 4.0.4 on 2022-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
